FROM python:3.12.3-bookworm

WORKDIR /volume

RUN python3 --version
RUN python3 -m pip --version

COPY ./requirements.txt .
RUN pip3 install -r requirements.txt

COPY ./requirements.yml .
RUN ansible-galaxy install -r requirements.yml

# Add Tini to handle process for gracefully shutdown and prevent zombie process
ENV TINI_VERSION v0.19.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini
ENTRYPOINT ["/tini", "--"]

# Run your program under Tini
CMD ["tail", "-f", "/dev/null"]